#The mybatis settings
mybatis:
  configLocations: classpath:mybatis/mybatis-config.xml
  mapperLocations: classpath:mybatis/mapper/*.xml
  typeAliasesPackage: com.model.dbuser

#Spring boot settings
spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.241.221:1521:orcl
    username: sgs
    password: sgs
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false

#Spring boot endpoints settings
endpoints:
  health:
    sensitive: false

#Spring boot management settings
management:
  security:
    enabled: false

server:
  port: 80

#Logging settings
logging:
  level: DEBUF
  file: ./weixinGZH/logs/weixinGZH.log